version: 2

project_name: gomc-ping

builds:
  - id: gomc-ping
    main: ./examples/basic/
    binary: gomc-ping
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
